"""
Swiss See Ballers — Live Draft Assistant
=========================================
Streamlit app for live use during the Oct 17, 2026 ESPN salary-cap auction
draft. Log every pick (player, team, price) as it happens on ESPN; this
recomputes, on every entry:

  - Live inflation: remaining league-wide budget vs. remaining projected
    value of the players still left to be drafted. Prices run "hot" or
    "cold" relative to the pre-draft baseline as the real draft unfolds,
    and this keeps recommendations honest about that instead of just
    replaying the static pre-draft board.
  - Your team's remaining budget, remaining roster slots, and Center count
    (capped at league max_centers) -> a suggested MAX BID per remaining
    player, so you never recommend a bid you can't actually afford once
    your other required slots are accounted for.

The player pool + league rules come from player_pool.csv / league_meta.json,
both generated by the last cell of fantasy_draft_2026_27_v2.ipynb — re-run
that notebook and this app's data refreshes; nothing you've logged in the
app is touched by that.

The draft log itself is persisted to draft_log.json after every change, so
a browser refresh or an app restart mid-draft doesn't lose anything logged
so far.
"""

import json
import unicodedata
from pathlib import Path

import pandas as pd
import streamlit as st

APP_DIR = Path(__file__).parent
POOL_CSV = APP_DIR / "player_pool.csv"
META_JSON = APP_DIR / "league_meta.json"
LOG_JSON = APP_DIR / "draft_log.json"

st.set_page_config(page_title="Live Draft Assistant", layout="wide")


def strip_accents(s: str) -> str:
    """'Jokić' -> 'Jokic' — so typing plain ASCII during a fast live draft
    still matches accented NBA names (Dončić, Šarić, Đurišić, ...)."""
    return "".join(c for c in unicodedata.normalize("NFKD", s) if not unicodedata.combining(c))


# ── Data loading ──────────────────────────────────────────────────────────
@st.cache_data
def load_pool() -> pd.DataFrame:
    return pd.read_csv(POOL_CSV)


@st.cache_data
def load_meta() -> dict:
    return json.loads(META_JSON.read_text())


def load_log() -> list[dict]:
    if LOG_JSON.exists():
        return json.loads(LOG_JSON.read_text())
    return []


def save_log(log: list[dict]) -> None:
    LOG_JSON.write_text(json.dumps(log, indent=2))


if not POOL_CSV.exists() or not META_JSON.exists():
    st.error(
        "player_pool.csv / league_meta.json not found in draft_app/. "
        "Run the last cell of fantasy_draft_2026_27_v2.ipynb first to generate them."
    )
    st.stop()

pool = load_pool()
meta = load_meta()

TEAM_NAMES = meta["team_names"]
YOUR_TEAM = meta["your_team_name"]
BUDGET_PER_TEAM = meta["budget_per_team"]
ROSTER_SIZE = meta["roster_size"]
TOTAL_DRAFTED = meta["total_drafted"]
MIN_BID = meta["min_bid"]
MAX_CENTERS = meta["max_centers"]

if "draft_log" not in st.session_state:
    st.session_state.draft_log = load_log()
log = st.session_state.draft_log


# ── Derived draft state ──────────────────────────────────────────────────
def is_center(player_id: int) -> bool:
    row = pool.loc[pool["PLAYER_ID"] == player_id, "POS_ELIGIBLE_STR"]
    if row.empty:
        return False
    return "C" in str(row.iloc[0]).split("/")


drafted_ids = {e["player_id"] for e in log}
available = pool[~pool["PLAYER_ID"].isin(drafted_ids)].copy()

spend = {t: 0 for t in TEAM_NAMES}
picks_count = {t: 0 for t in TEAM_NAMES}
centers_drafted = {t: 0 for t in TEAM_NAMES}
for e in log:
    spend[e["team"]] = spend.get(e["team"], 0) + e["price"]
    picks_count[e["team"]] = picks_count.get(e["team"], 0) + 1
    if is_center(e["player_id"]):
        centers_drafted[e["team"]] = centers_drafted.get(e["team"], 0) + 1

remaining_budget = {t: BUDGET_PER_TEAM - spend[t] for t in TEAM_NAMES}
remaining_slots = {t: ROSTER_SIZE - picks_count[t] for t in TEAM_NAMES}

your_remaining_budget = remaining_budget[YOUR_TEAM]
your_remaining_slots = remaining_slots[YOUR_TEAM]
your_centers = centers_drafted[YOUR_TEAM]

# ── Sidebar: strategy + your team status ─────────────────────────────────
st.sidebar.title(meta["league_name"])
st.sidebar.caption(f"Projections generated: {meta.get('generated_at', '?')[:16].replace('T', ' ')}")

strategy = st.sidebar.radio(
    "Strategie", ["Punt (6-cat)", "Balanced (10-cat)"], index=0
)
value_col = "EST_$PUNT" if strategy.startswith("Punt") else "EST_$BAL"

st.sidebar.markdown("---")
st.sidebar.subheader(f"🏆 {YOUR_TEAM}")
st.sidebar.metric("Restbudget", f"${your_remaining_budget}")
st.sidebar.metric("Offene Roster-Slots", f"{your_remaining_slots} / {ROSTER_SIZE}")
st.sidebar.metric("Center gedraftet", f"{your_centers} / {MAX_CENTERS}")

if your_remaining_slots > 0:
    max_bid_cap = your_remaining_budget - max(your_remaining_slots - 1, 0) * MIN_BID
else:
    max_bid_cap = 0
st.sidebar.metric("Max. Gebot (theoretisch)", f"${max(max_bid_cap, 0)}")
st.sidebar.caption(
    "= Restbudget minus $1 Mindestgebot für jeden weiteren offenen Slot — "
    "mehr kannst du für EINEN Spieler nicht bieten, ohne die restlichen Slots zu gefährden."
)

st.sidebar.markdown("---")
st.sidebar.subheader("Alle Teams — Restbudget")
budget_df = pd.DataFrame(
    {
        "Team": TEAM_NAMES,
        "Rest-$": [remaining_budget[t] for t in TEAM_NAMES],
        "Slots offen": [remaining_slots[t] for t in TEAM_NAMES],
    }
).sort_values("Rest-$", ascending=False)
st.sidebar.dataframe(budget_df, hide_index=True, width='stretch')

# ── Live inflation ────────────────────────────────────────────────────────
league_remaining_budget = sum(remaining_budget.values())
total_picks_so_far = len(log)
players_still_to_be_drafted = max(TOTAL_DRAFTED - total_picks_so_far, 0)

baseline_pool_value = (
    available.sort_values(value_col, ascending=False)
    .head(players_still_to_be_drafted)[value_col]
    .sum()
)
inflation = (
    league_remaining_budget / baseline_pool_value if baseline_pool_value > 0 else 1.0
)

available["LIVE_$"] = (available[value_col] * inflation).round(1).clip(lower=MIN_BID)
available["YOUR_MAX_BID"] = available["LIVE_$"].clip(upper=max(max_bid_cap, MIN_BID))
# Don't recommend spending your whole cap-minus-reserve on someone worth far less live.
available.loc[available["LIVE_$"] < available["YOUR_MAX_BID"], "YOUR_MAX_BID"] = available["LIVE_$"]

center_capped = your_centers >= MAX_CENTERS
available["CENTER_ONLY"] = available["POS_ELIGIBLE_STR"] == "C"
if center_capped:
    available.loc[available["CENTER_ONLY"], "YOUR_MAX_BID"] = 0

st.title("🏀 Live Draft Assistant")
c1, c2, c3 = st.columns(3)
c1.metric("Inflation", f"{inflation:.2f}×", help="Restbudget der Liga ÷ Restwert der noch draftbaren Spieler. >1 = Preise laufen heiß, <1 = Schnäppchen.")
c2.metric("Picks geloggt", f"{total_picks_so_far} / {TOTAL_DRAFTED}")
c3.metric("Spieler verfügbar", len(available))

if center_capped:
    st.warning(
        f"Center-Limit erreicht ({your_centers}/{MAX_CENTERS}) — reine Center "
        "(POS_ELIGIBLE = 'C') werden mit $0 Max-Gebot angezeigt, da nicht rosterbar."
    )

# ── Pick-entry form ───────────────────────────────────────────────────────
# The search box lives OUTSIDE the st.form so every keystroke reruns and
# narrows the selectbox immediately (widgets inside a form don't rerun
# until submit). Matching strips accents on both sides, so a fast "Jokic"
# during a live draft still finds "Nikola Jokić".
st.subheader("Pick eintragen")
search_query = st.text_input(
    "Spieler suchen", placeholder="Name oder Teil davon — Akzente egal (z.B. 'jokic')"
)


def _matches(name: str, query: str) -> bool:
    if not query:
        return True
    return strip_accents(query).lower() in strip_accents(name).lower()


filtered = available[available["PLAYER_NAME"].apply(lambda n: _matches(n, search_query))]
filtered = filtered.sort_values("PLAYER_NAME")
player_options = filtered["PLAYER_NAME"].tolist()

with st.form("log_pick", clear_on_submit=True):
    fc1, fc2, fc3, fc4 = st.columns([3, 2, 1, 1])
    picked_name = fc1.selectbox(
        f"Treffer ({len(player_options)})", player_options, index=None, placeholder="Spieler wählen…"
    )
    picked_team = fc2.selectbox("Team", TEAM_NAMES, index=TEAM_NAMES.index(YOUR_TEAM))
    picked_price = fc3.number_input("Preis ($)", min_value=MIN_BID, max_value=BUDGET_PER_TEAM, value=MIN_BID, step=1)
    submitted = fc4.form_submit_button("Eintragen", width='stretch')

    if submitted:
        if picked_name is None:
            st.error("Bitte einen Spieler auswählen.")
        else:
            pid = int(pool.loc[pool["PLAYER_NAME"] == picked_name, "PLAYER_ID"].iloc[0])
            log.append({"player_id": pid, "player_name": picked_name, "team": picked_team, "price": int(picked_price)})
            save_log(log)
            st.rerun()

# ── Draft log + undo ──────────────────────────────────────────────────────
with st.expander(f"Draft-Log ({len(log)} Picks) — zum Korrigieren aufklappen", expanded=False):
    if log:
        log_df = pd.DataFrame(log).iloc[::-1].reset_index(drop=True)
        log_df.index = range(len(log) - 1, -1, -1)
        st.dataframe(log_df[["player_name", "team", "price"]], width='stretch')

        remove_idx = st.selectbox(
            "Eintrag entfernen (Index)",
            options=list(range(len(log))),
            format_func=lambda i: f"#{i}: {log[i]['player_name']} — {log[i]['team']} (${log[i]['price']})",
            index=None,
            placeholder="Index wählen…",
        )
        rc1, rc2 = st.columns(2)
        if rc1.button("Ausgewählten Eintrag entfernen") and remove_idx is not None:
            log.pop(remove_idx)
            save_log(log)
            st.rerun()
        if rc2.button("⚠️ Kompletten Draft zurücksetzen"):
            st.session_state.draft_log = []
            save_log([])
            st.rerun()
    else:
        st.caption("Noch keine Picks geloggt.")

# ── Recommendation board ──────────────────────────────────────────────────
st.subheader("Verfügbare Spieler — live bewertet")

all_positions = ["PG", "SG", "SF", "PF", "C"]
pos_filter = st.multiselect("Position filtern", all_positions, default=[])
board = available.copy()
if pos_filter:
    board = board[
        board["POS_ELIGIBLE_STR"].apply(lambda s: any(p in str(s).split("/") for p in pos_filter))
    ]

board = board.sort_values("LIVE_$", ascending=False)

display_cols = [
    "PLAYER_NAME", "POS_ELIGIBLE_STR", "CURRENT_TEAM_ABBR", "AGE", "RISK_FLAG",
    "LIVE_$", "YOUR_MAX_BID", value_col,
    "PRED_PTS_PG", "PRED_AST_PG", "PRED_REB_PG", "PRED_STL_PG", "PRED_BLK_PG",
    "PRED_FG3M_PG", "PRED_FT_PCT",
]
rename = {
    "PLAYER_NAME": "Spieler", "POS_ELIGIBLE_STR": "Pos", "CURRENT_TEAM_ABBR": "Team",
    "AGE": "Alter", "RISK_FLAG": "Risiko", "LIVE_$": "Live $", "YOUR_MAX_BID": "Dein Max-Gebot",
    value_col: "Basis-$ (pre-draft)",
    "PRED_PTS_PG": "PTS", "PRED_AST_PG": "AST", "PRED_REB_PG": "REB",
    "PRED_STL_PG": "STL", "PRED_BLK_PG": "BLK", "PRED_FG3M_PG": "3PM", "PRED_FT_PCT": "FT%",
}
st.dataframe(
    board[display_cols].rename(columns=rename).head(120),
    width='stretch',
    height=600,
    hide_index=True,
)
